name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # todo dia à meia-noite
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: sarasmorais
          outputs: |
            ./github-contribution-grid-snake.svg

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "generated contribution snake"
          add: "github-contribution-grid-snake.svg"
